### ISSUE TITLE
unable to download some images with the current save_image function

### ISSUE THREAD

**Issue by jtonglet** [stevejpapad/verite-benchmark#3]
Hi,

Thanks for the very interesting dataset.

I tried loading the dataset with the provided script. However, not all images can be downloaded with the save_image function. For example, it does not work for the url "https://archive.ph/NMmvK/4805e1e565fef7788261f8b99fb0cbbae7b841f1.jpg" and other "https://archive" urls. In total, I was unable to download 37 images, corresponding to 74 instances of VERITE.

Some of the URLs cannot even be reached by accessing them in a standard web browser. 

Is there any alternative to build the original dataset?

**Comment by stevejpapad** [comment]
Hi,

I appreciate your interest in the VERITE dataset!

Kindly send an email to stefpapad@iti.gr to request access to the missing images. It is recommended to use your academic email address and explicitly mention that you intend to use the dataset exclusively for research purposes.

**Comment by jtonglet** [comment]
Thanks for your answer. I have sent a mail and will close the issue.
